[build]
    command = "npm run build"
    publish = "dist"
    commandOrigin: config
    publish: /opt/build/repo/dist
    publishOrigin: config
    headers:


[[redirects]]
    from = "/*"
    to = "/src/index.html"
    status = 200

[[headers]]
    for = "/*"
        [headers.values]
        Access-Control-Allow-Origin = "*"